version: '3.2'

services:
  chall:
    build: ./chall
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "FLAG=ASIS{test-flag}"
  redis:
    image: redis@sha256:eadf354977d428e347d93046bb1a5569d701e8deb68f090215534a99dbcb23b9
    restart: always
